version: '3.8'

services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '5000:5000'
        environment:
            - NODE_ENV=development
            - DB_SERVER=postgresql://postgres:SupaBasePass01!@db.pbdodcjhafdkivnkctal.supabase.co:5432/postgres
            - DB_USER=postgres
            - DB_PASSWORD=SupaBasePass01!
            - DB_NAME=postgres
            - DB_PORT=5432
        networks:
            - dashboardiot_network
        command: ['/bin/sh', '-c', 'cd backend && npm run dev']

    frontend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '5173:5173'
        depends_on:
            - backend
        networks:
            - dashboardiot_network
        command: ['/bin/sh', '-c', 'cd frontend && npm run dev']

networks:
    dashboardiot_network:
        driver: bridge
