version: '3.8'

services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '5000:5000'
        env_file:
            - .env # ✅ Load all environment variables from .env
        networks:
            - dashboardiot_network
        working_dir: /app/backend # ✅ Set correct working directory
        command: ['npm', 'run', 'dev'] # ✅ Properly run the backend

    frontend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '5173:5173'
        depends_on:
            - backend
        networks:
            - dashboardiot_network
        working_dir: /app/frontend # ✅ Set correct working directory
        command: ['npm', 'run', 'dev'] # ✅ Properly run the frontend

networks:
    dashboardiot_network:
        driver: bridge
