version: '3.8'

services:
    backend:
        build: ./backend
        ports:
            - '5000:5000'
        environment:
            - NODE_ENV=production
            - DB_SERVER=mssql_container
            - DB_PASSWORD=mysql123
            - DB_NAME=iot_dashboard
        depends_on:
            - mssql
        networks:
            - dashboardiot_network

    frontend:
        build: ./frontend
        ports:
            - '3000:3000'
        depends_on:
            - backend
        networks:
            - dashboardiot_network

    mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: mssql_container
        ports:
            - '1433:1433'
        environment:
            SA_PASSWORD: 'mysql123'
            ACCEPT_EULA: 'Y'
        networks:
            - dashboardiot_network

networks:
    dashboardiot_network:
        driver: bridge
